version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: event-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventUser
      POSTGRES_PASSWORD: eventPW
    ports:
      - "5433:5432"   # <— hier ändern!
    volumes:
      - event-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d eventdb"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eventdb
      SPRING_DATASOURCE_USERNAME: eventUser
      SPRING_DATASOURCE_PASSWORD: eventPW
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8090:8090"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8090

volumes:
  event-data:
